### ISSUE TITLE
Notifications not even trying to appear

### ISSUE THREAD

**Issue by crudebuster** [Alex313031/thorium-win7#50]
**System Details**
 - OS: Windows 7 SP1 64Bit
 - Thorium AVX_119.0.6045.214

**Problem**
Site Notifications are gone. No sign of them whatsoever. Nothing for download, instant messages, emails, only sounds by an extension I use to warn after a successful download.

**Additional Notes**
After I upgraded from M109 to M119 I knew I had to refresh passwords and such but after I did it no notification toasts appear whatsoever... I noticed too late and now the password manager won't save anything since I backtracked and went back to use M109. 
I hope it's something dumb I did but I'm afraid the thing simply doesn't work because of some dumbassity I did and now I need to redo the god damn profile and account, I guess.

**Comment by crudebuster** [comment]
I suppose so... welp... how do we bring them back then? just revert these?

**Comment by Alex313031** [comment]
@crudebuster Both of these were reverted in the M122 version. Are you using that version and the problem still persists?

Does this problem happen in Supermium M122?

**Comment by crudebuster** [comment]
I've only tried the beta but I'll check it again.

**Comment by Alex313031** [comment]
@crudebuster @llExSt I think I know why it is. I recently enabled a change to make notifications less intrusive, but some people want them.

Go to `chrome://settings/content/notifications` and change it from "Use quieter messaging" to "Sites can ask to send notifications"

**Comment by crudebuster** [comment]
Done that, the setting was already in, the notification engine seems completely disabled.

**Comment by crudebuster** [comment]
In Supermium 124 the notifications work again in Win7 so i'll wait for your update to Thorium.

**Comment by Nvdtn19** [comment]
> @crudebusterỒ. Trong trường hợp đó, có lẽ win32ss sẽ phải sửa lỗi này.

Do you have plans to update Thorium to match Supermium's version? The notification issues is still not fixed.
